apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: promoter
rules:
- apiGroups:
  - apps/v1
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
- apiGroups:
  - v1
  resources:
  - services
  verbs:
  - create
  - update
  - delete
- apiGroups:
  - split.smi-spec.io/v1alpha1
  resources:
  - trafficsplits
  verbs:
  - create
  - update
  - delete
- apiGroups:
  - mesh.demos.io/v1
  resources:
  - canaries
  verbs:
  - '*'
