apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: quarantines.autopiot.example.io
spec:
  group: autopiot.example.io
  names:
    kind: Quarantine
    listKind: QuarantineList
    plural: quarantines
    singular: quarantine
  scope: Namespaced
  subresources:
    status: {}
  versions:
  - name: v1
    served: true
    storage: true
